// Regenerates src/world/brightStarsData.ts from the raw Yale Bright Star Catalog
// (src/world/data/bsc5-short.json). Run: `npm run gen:stars`.
//
// The raw catalogue is ~931 KB and full of fields we don't render (HR/constellation/Flamsteed) plus
// verbose sexagesimal strings ("00h 05m 09.9s"). We only need, per star: direction (RA/Dec),
// visual magnitude, and blackbody colour temperature. This bakes those four into a compact columnar
// integer object so the shipped module is ~180 KB (~64 KB gzip) instead of the raw file's ~171 KB
// gzip — and parses far faster (plain numbers, no regex at load).

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const SRC = join(here, '..', 'src', 'world', 'data', 'bsc5-short.json');
const OUT = join(here, '..', 'src', 'world', 'brightStarsData.ts');

const RA_RE = /(\d+)h\s*(\d+)m\s*([\d.]+)s/;
const DEC_RE = /([+-])\s*(\d+)\D+?(\d+)\D+?(\d+)/;

// Fixed-point scales: 0.01° in RA/Dec (~36″, far finer than a background needs) and 0.01 mag.
const RA_SCALE = 100;
const DEC_SCALE = 100;
const MAG_SCALE = 100;
const DEFAULT_MAG = 8;
const DEFAULT_K = 5800;

const raw = JSON.parse(readFileSync(SRC, 'utf8'));
const ra = [], dec = [], mag = [], k = [];
for (const s of raw) {
  const mRa = RA_RE.exec(s.RA);
  const mDec = DEC_RE.exec(s.Dec);
  if (!mRa || !mDec) continue;
  const raDeg = (+mRa[1] + +mRa[2] / 60 + +mRa[3] / 3600) * 15;
  const decDeg = (mDec[1] === '-' ? -1 : 1) * (+mDec[2] + +mDec[3] / 60 + +mDec[4] / 3600);
  ra.push(Math.round(raDeg * RA_SCALE));
  dec.push(Math.round(decDeg * DEC_SCALE));
  mag.push(Math.round((s.V !== undefined && s.V !== '' ? +s.V : DEFAULT_MAG) * MAG_SCALE));
  k.push(s.K !== undefined && s.K !== '' ? Math.round(+s.K) : DEFAULT_K);
}

const out = `// GENERATED by scripts/genBrightStars.mjs from the Yale Bright Star Catalog — do not edit by hand.
// Compact columnar form of the ${ra.length} catalogued stars, keeping only what the starfield draws.
// Decoded in brightStars.ts. RA/Dec are fixed-point degrees (÷${RA_SCALE}), mag is ÷${MAG_SCALE}, k is Kelvin.

export const RA_SCALE = ${RA_SCALE};
export const DEC_SCALE = ${DEC_SCALE};
export const MAG_SCALE = ${MAG_SCALE};

export interface BrightStarData {
  /** right ascension, fixed-point degrees (divide by RA_SCALE) */
  ra: number[];
  /** declination, fixed-point degrees (divide by DEC_SCALE) */
  dec: number[];
  /** visual magnitude, fixed-point (divide by MAG_SCALE) */
  mag: number[];
  /** blackbody colour temperature, Kelvin */
  k: number[];
}

export const BRIGHT_STARS: BrightStarData = {
  ra: [${ra.join(',')}],
  dec: [${dec.join(',')}],
  mag: [${mag.join(',')}],
  k: [${k.join(',')}]
};
`;

writeFileSync(OUT, out);
console.log(`wrote ${OUT}: ${ra.length} stars`);
